name: My First Workflow

on: [push]
jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "Hello World"
      - name: multiline script
        run: |
          node -v
          npm -v
      - name: Python Command
        run: |
          import platform
          print(platform.processor())
        shell: python
  run-windows-command:
    runs-on: windows-latest
    steps:
      - name: directory power-shell
        run: Get-Location
      - name: directory bash
        run: pwd
        shell: bash
  run-mac-command:
    runs-on: macos-latest
    steps:
      - name: macOS
        run: java -version
